### ISSUE TITLE
gym.error.NameNotFound: Environment `gym_cityflow:cityflow` doesn't exist.

### ISSUE THREAD

**Issue by krayF1sh** [MaxVanDijck/gym-cityflow#1]
Hey there,

I assume that the package has been installed properly because when I import it I don't get any errors. I tried to reproduce your example code. I even tried to run the tests files. I am pasting here what I got by trying to run the `test1.py` from the project folder:

![Στιγμιότυπο οθόνης 2022-04-12 183006](https://user-images.githubusercontent.com/42109143/162998977-5935e9d4-9da1-44a4-a5a7-ab4a4f9aebc2.png)

Could you please shed some light on this?

**Comment by MaxVanDijck** [comment]
My mistake, Looks like I previously made changes to the gym environment and did not check the example env inits. Have fixed the test examples in https://github.com/MaxVanDijck/gym-cityflow/pull/2 

```
env = gym.make('gym_cityflow:cityflow-v0', 
               configPath = 'sample_path/sample_config.json',
               episodeSteps = 3600)
```
Was supposed to be:
```
env = gym.make('cityflow-v0', 
               configPath = 'sample_path/sample_config.json',
               episodeSteps = 3600)
```

**Comment by MaxVanDijck** [comment]
This is the correct test2.py output:
![image](https://user-images.githubusercontent.com/50382570/163056147-c7106703-46f5-41cf-a39d-9d6345cb4d6a.png)

`MultiDiscrete([9])` Means that the environment has a single intersection with up to 9 action states (0->8)

`Dict(intersection_1_1:MultiDiscrete([[827 827]
 [827 827] ...` is the observation example with the maximum values for each lane pair. [827, 827] = 827 cars on the entry lane and 827 cars on the exit lane

`[['intersection_1_1', -2014539260598.9158]]` is the reward for each intersection. For each waiting car, it calculates an negative exponentially growing value until the car is allowed through eg. a car waiting for 10 seconds = -np.exp(10)
The goal of this environment is to maximise the reward value i.e reduce the total wait time at each timestep
